### ISSUE TITLE
PIP package for version 1.2.3 missing utils folder

### ISSUE THREAD

**Issue by devmonkey22** [deplicate/deplicate#2]
Installed 1.2.3 on Windows 10 with python 3.6.5.

```
>>> import duplicate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".virtualenvs\Duplicates-1Bkne2Yf\lib\site-packages\duplicate\__init__.py", line 13, in <module>
    from .core import CACHE
  File ".virtualenvs\Duplicates-1Bkne2Yf\lib\site-packages\duplicate\core.py", line 17, in <module>
    from .structs import Cache, DupInfo, FileInfo, FilterType, SkipException
  File ".virtualenvs\Duplicates-1Bkne2Yf\lib\site-packages\duplicate\structs.py", line 13, in <module>
    from .utils.fs import blkdevice, blksize
ModuleNotFoundError: No module named 'duplicate.utils'
```

I was able to download the source package and just copy into my virtualenv at least.

**Comment by earthbound19** [comment]
I ran into this too, and don't know what to download from where and copy where in a Python 3.6 install.

**Comment by kallol-oto** [comment]
I am also getting the same error. Please fix it ASAP

**Comment by CapitaineNemo** [comment]
I am also getting the same issue. Could you fix it?

**Comment by amadis** [comment]
Same error,
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
deplicate in c:\program files (x86)\python38-32\lib\site-packages (1.2.3)

**Comment by anovickis** [comment]
I'm sure I solved this some unpythonic way but I have to get past the problem. Here's what I did:

Go to wherever pip installed this package on your system
In my case this was
C:\Users\Alex P. Novickis.QCE3X\AppData\Roaming\Python\Python310\site-packages\duplicate

make a folder called utils
download this entire package from here as zip, and copy out the contents of the zip's utils folder to this new folder you made

>> import duplicate
>>
