### ISSUE TITLE
duplicate.utils

### ISSUE THREAD

**Issue by moiseyo** [deplicate/deplicate#3]
After installation python  3.8 

    import duplicate
    duplicate.find('c:/mydev/python3')

run 
 File "C:/MyDev/python3/temp/1.py", line 33, in <module>
    import duplicate
  File "C:\Python36\lib\site-packages\duplicate\__init__.py", line 13, in <module>
    from .core import CACHE
  File "C:\Python36\lib\site-packages\duplicate\core.py", line 17, in <module>
    from .structs import Cache, DupInfo, FileInfo, FilterType, SkipException
  File "C:\Python36\lib\site-packages\duplicate\structs.py", line 13, in <module>
    from .utils.fs import blkdevice, blksize
ModuleNotFoundError: No module named 'duplicate.utils'

**Comment by ptrstn** [comment]
I can confirm this issue

**Comment by dev107** [comment]
Same issue on Ubuntu 19.10:

```
Traceback (most recent call last):
  File "filemon/deplic.py", line 1, in <module>
    import duplicate
  File "/usr/local/lib/python3.7/dist-packages/duplicate/__init__.py", line 13, in <module>
    from .core import CACHE
  File "/usr/local/lib/python3.7/dist-packages/duplicate/core.py", line 17, in <module>
    from .structs import Cache, DupInfo, FileInfo, FilterType, SkipException
  File "/usr/local/lib/python3.7/dist-packages/duplicate/structs.py", line 13, in <module>
    from .utils.fs import blkdevice, blksize
ModuleNotFoundError: No module named 'duplicate.utils'
```

**Comment by H3pha3st0s** [comment]
HI i saw earlier it said you fixed the issue am still running into it.


Traceback (most recent call last):
  File "c:\Users\M\Desktop\scripts\sorter\test.py", line 1, in <module>
    from duplicate import find
  File "C:\Users\M\AppData\Local\Programs\Python\Python38-32\lib\site-packages\duplicate\__init__.py", line 13, in <module>
    from .core import CACHE
  File "C:\Users\M\AppData\Local\Programs\Python\Python38-32\lib\site-packages\duplicate\core.py", line 17, in <module>
    from .structs import Cache, DupInfo, FileInfo, FilterType, SkipException
  File "C:\Users\M\AppData\Local\Programs\Python\Python38-32\lib\site-packages\duplicate\structs.py", line 13, in <module>
    from .utils.fs import blkdevice, blksize
ModuleNotFoundError: No module named 'duplicate.utils'
PS C:\Users\M\Desktop\scripts\sorter>

**Comment by benbaessler** [comment]
I just tried to run my code and then this came up: ```
Traceback (most recent call last):
  File "/Users/benbaessler/Documents/Projects/Cleaner/test.py", line 1, in <module>
    import duplicate
  File "/Users/benbaessler/opt/anaconda3/lib/python3.7/site-packages/duplicate/__init__.py", line 13, in <module>
    from .core import CACHE
  File "/Users/benbaessler/opt/anaconda3/lib/python3.7/site-packages/duplicate/core.py", line 17, in <module>
    from .structs import Cache, DupInfo, FileInfo, FilterType, SkipException
  File "/Users/benbaessler/opt/anaconda3/lib/python3.7/site-packages/duplicate/structs.py", line 13, in <module>
    from .utils.fs import blkdevice, blksize
ModuleNotFoundError: No module named 'duplicate.utils'
```

**Comment by benbaessler** [comment]
I tried to run my code and then this came up:
**Traceback (most recent call last):
  File "/Users/benbaessler/Documents/Projects/Cleaner/test.py", line 1, in <module>
    import duplicate
  File "/Users/benbaessler/opt/anaconda3/lib/python3.7/site-packages/duplicate/__init__.py", line 13, in <module>
    from .core import CACHE
  File "/Users/benbaessler/opt/anaconda3/lib/python3.7/site-packages/duplicate/core.py", line 17, in <module>
    from .structs import Cache, DupInfo, FileInfo, FilterType, SkipException
  File "/Users/benbaessler/opt/anaconda3/lib/python3.7/site-packages/duplicate/structs.py", line 13, in <module>
    from .utils.fs import blkdevice, blksize
ModuleNotFoundError: No module named 'duplicate.utils'**

**Comment by lejedi76** [comment]
To fix the ModuleNotFoundError :
download the source of the repository, extract the file.
Put the utils folder in the site-packages/duplicate/


/usr/local/lib/python3.7/dist-packages/duplicate/utils
C:\Users\M\AppData\Local\Programs\Python\Python38-32\lib\site-packages\duplicate\utils
/Users/benbaessler/opt/anaconda3/lib/python3.7/site-packages/duplicate/utils/

**Comment by surfer190** [comment]
Need to fix this in the package itself and not rely on users doing this workaround please.

Furthermore why is the module called `duplicate` but the package called `deplicate` - let us just save time and confustion and use `deplicate` for both.
