### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by AdityaKane2001** [deplicate/deplicate#8]
```
!pip install deplicate
import duplicate

duplicate.find('/content/train')
```
Ran this code in colab

Got this error: 

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-ea4e2f54cc91> in <module>()
      1 get_ipython().system('pip install deplicate')
----> 2 import duplicate
      3 
      4 duplicate.find('/content/train')

2 frames
/usr/local/lib/python3.6/dist-packages/duplicate/__init__.py in <module>()
     11 from __future__ import absolute_import
     12 
---> 13 from .core import CACHE
     14 from .deplicate import Deplicate
     15 from .structs import Cache, ResultInfo, SkipException

/usr/local/lib/python3.6/dist-packages/duplicate/core.py in <module>()
     15 import xxhash
     16 
---> 17 from .structs import Cache, DupInfo, FileInfo, FilterType, SkipException
     18 from .utils.fs import (blksize, checksum, fsdecode, is_archived, is_hidden,
     19                        is_os64, is_system, remove, sidesum, signature,

/usr/local/lib/python3.6/dist-packages/duplicate/structs.py in <module>()
     11 from threading import RLock
     12 
---> 13 from .utils.fs import blkdevice, blksize
     14 
     15 # from ssd import is_ssd

ModuleNotFoundError: No module named 'duplicate.utils'
```

**Comment by gsnoek** [comment]
Experiencing same issue. The utils and utils/fs folders are not getting installed under anaconda in windows 10.  I tried forcing it a few different ways with no luck. 

First I modified `setup.py` from 

```python
    packages=['duplicate']
```

to:

```python
    packages=['duplicate', 'duplicate/utils', 'duplicate/utils/fs']
```

This allowed the correct folders to get installed.  But since I was running under anaconda, I also had to do `conda install pywin32` in my environment to get rid of the next error.  

But now I'm hitting this error and giving up as I don't feel like recoding the whole thing right now. 

```
  File "D:\Anaconda3\envs\nzb\lib\site-packages\duplicate\__init__.py", line 25, in find
    d.find(onerror, notify)
  File "D:\Anaconda3\envs\nzb\lib\site-packages\duplicate\deplicate.py", line 156, in find
    self._find(onerror, notify)
  File "D:\Anaconda3\envs\nzb\lib\site-packages\duplicate\deplicate.py", line 136, in _find
    self._scan(onerror, notify)
  File "D:\Anaconda3\envs\nzb\lib\site-packages\duplicate\deplicate.py", line 112, in _scan
    self._dupinfo, self._scnerrors = scandups(
  File "D:\Anaconda3\envs\nzb\lib\site-packages\duplicate\core.py", line 460, in scandups
    dupinfo = DupInfo(FilterType.ID, dupdict, errlist)
  File "D:\Anaconda3\envs\nzb\lib\site-packages\duplicate\structs.py", line 105, in __init__
    super(DupInfo, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```
